services:
  postgis:
    image: postgis/postgis:latest  # PostgreSQL 15 with PostGIS 3.3
    container_name: postgis
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432" # Expose the database on localhost:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80" # Expose the web interface on localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: "ilisi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ilisi"


volumes:
  postgis_data:
