services:
  postgis:
    image: postgis/postgis:15-3.3  # PostgreSQL 15 with PostGIS 3.3
    container_name: postgis
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432" # Expose the database on localhost:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
